# Generated by Django 5.2 on 2025-05-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edificio', models.CharField(max_length=100)),
                ('escala', models.CharField(max_length=100)),
                ('materiales', models.CharField(max_length=200)),
                ('construccion', models.PositiveIntegerField(help_text='Años de contruccion')),
                ('proposito', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=200)),
                ('nivel', models.CharField(max_length=200)),
            ],
        ),
    ]
