# Generated by Django 5.2 on 2025-05-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edificios', '0002_alter_edificio_escala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='edificio',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='materiales',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='nivel',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='proposito',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='ubicacion',
            field=models.TextField(max_length=200),
        ),
    ]
