# Generated by Django 5.2 on 2025-05-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edificios', '0003_alter_edificio_edificio_alter_edificio_materiales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='edificio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='materiales',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='nivel',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='proposito',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='ubicacion',
            field=models.TextField(),
        ),
    ]
