# Generated by Django 5.2 on 2025-05-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edificios', '0004_alter_edificio_edificio_alter_edificio_materiales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='construccion',
            field=models.PositiveIntegerField(help_text='Año de construcción'),
        ),
    ]
