# Generated by Django 5.2 on 2025-05-21 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Disenadores', '0001_initial'),
        ('Museos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloInteractivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('disenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Disenadores.disenadorux')),
                ('museo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Museos.museo')),
            ],
        ),
    ]
